### ISSUE TITLE
tests failing with go-libp2p-testing v0.4.x

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-tcp-transport#85]
with v0.4.0:
```
=== RUN   TestTcpTransport/github.com/libp2p/go-libp2p-testing/suites/transport.SubtestStress50Conn10Stream50Msg
panic: Fail in goroutine after TestTcpTransport/github.com/libp2p/go-libp2p-testing/suites/transport.SubtestStress1Conn100Stream100Msg has completed

goroutine 221 [running]:
testing.(*common).Fail(0xc000902a80)
        /usr/local/Cellar/go/1.16.6/libexec/src/testing/testing.go:697 +0x125
testing.(*common).Error(0xc000902a80, 0xc000977f98, 0x1, 0x1)
        /usr/local/Cellar/go/1.16.6/libexec/src/testing/testing.go:797 +0x78
github.com/libp2p/go-libp2p-testing/suites/transport.echoStream(0xc000902a80, 0x1746df8, 0xc00061cd00)
        /Users/marten/src/go/pkg/mod/github.com/libp2p/go-libp2p-testing@v0.4.0/suites/transport/stream_suite.go:109 +0x26d
created by github.com/libp2p/go-libp2p-testing/suites/transport.goServe.func1.1
        /Users/marten/src/go/pkg/mod/github.com/libp2p/go-libp2p-testing@v0.4.0/suites/transport/stream_suite.go:145 +0x4b
exit status 2
FAIL    github.com/libp2p/go-tcp-transport      0.374s
```

With v0.4.1 the test `SubtestStress1Conn1Stream1Msg` hangs indefinitely. Apart from fixing this test failure, we probably want to add a test timeout.

**Comment by marten-seemann** [comment]
The problem seems to be in https://github.com/libp2p/go-libp2p-testing/blob/8852a73079910a9b425fb7deae29568bf767649e/suites/transport/stream_suite.go#L115-L150:
We don't close the connection before the `echo` hasn't returned, but `echo` won't return before `AcceptStream` has returned an error, which only happens when the connection is closed.
